version: '3.8'

services:
  postgres:
    image: postgres:13

    environment:
      POSTGRES_DB: ItamDB
      POSTGRES_USER: son
      POSTGRES_PASSWORD: 2510
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command : start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  postgres_data: